<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FB_PizzaAmericanStyle" Id="{cb40c609-3f26-4c2a-bce6-73adf6f1a66e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_PizzaAmericanStyle IMPLEMENTS I_Pizza
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetPrice" Id="{b18f3b20-fa10-4361-988b-e78b81243b43}">
      <Declaration><![CDATA[METHOD PUBLIC GetPrice : LREAL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[GetPrice := 4.2;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_PizzaAmericanStyle">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_PizzaAmericanStyle.GetPrice">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>